[project]
name = "lab01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "McEnigma24", email = "wojciech.mackowiak24@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "pre-commit>=4.6.2",
    "pydantic-settings>=2.15.0",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.4",
    "scikit-learn>=1.9.1",
    "uvicorn>=0.54.0",
]

[project.scripts]
lab01 = "lab01:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-dotenv>=0.5.2",
]
